import { Component } from '@angular/core';
import { Http, Headers } from '@angular/http';


@Component({
    selector: 'twitter',
    templateUrl: 'app/Views/twitter.component.html',
})

export class TwitterComponent {
    title = 'app works!';
    searchquery = '';
    tweetsdata: any;

    constructor(private http: Http) {
        
    }

    makecall() {
        var headers = new Headers();

        headers.append('Content-Type', 'application/X-www-form-urlencoded');

        this.http.post('http://localhost:3000/hometimeline', { headers: headers }).subscribe((res) => { this.tweetsdata = res.json().data.statuses; });
        //return this.http.get('http://localhost:3000/hometimeline', { headers: headers }).subscribe((res) => {
            //this.tweetsdata = res.json().data.statuses;
        //});
    }

    searchcall() {
        var headers = new Headers();
        var searchterm = 'query=' + this.searchquery;

        headers.append('Content-Type', 'application/X-www-form-urlencoded');

        this.http.post('http://localhost:3000/search', searchterm, { headers: headers }).subscribe((res) => {
            this.tweetsdata = res.json().data.statuses;
        });
    }

    hometimelinecall() {
        var headers = new Headers();

        headers.append('Content-Type', 'application/X-www-form-urlencoded');

        this.http.get('http://localhost:3000/hometimeline', { headers: headers }).subscribe((res) => {
            this.tweetsdata = [{
                created_at: 'Fri Oct 07 08:01:29 +0000 2016',
                id: 784302612610854900,
                id_str: '784302612610854914',
                text: '� thanks for giving me a good chuckle, but sorry about your holiday money dude https://t.co/ROLwgSSsNR',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 45594696,
                    id_str: '45594696',
                    name: 'Hannibal Lecterford',
                    screen_name: 'lomadia',
                    location: 'UK',
                    description: 'Gamer, cat lover, really likes raiding tombs - an unhealthy amount. Also a bit of a hoarder. I also stream on Twitch! Artwork by @NinaSerena & @ScribbleToons',
                    url: 'https://t.co/RTpHrjTQzo',
                    entities: [Object],
                    protected: false,
                    followers_count: 198946,
                    friends_count: 579,
                    listed_count: 584,
                    created_at: 'Mon Jun 08 15:50:33 +0000 2009',
                    favourites_count: 9556,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 38717,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '2D0F07',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/45594696/1466445904',
                    profile_link_color: '1E6D7D',
                    profile_sidebar_border_color: '000000',
                    profile_sidebar_fill_color: '180703',
                    profile_text_color: 'AB5F24',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: true,
                quoted_status_id: 784302396415422500,
                quoted_status_id_str: '784302396415422464',
                quoted_status:
                {
                    created_at: 'Fri Oct 07 08:00:37 +0000 2016',
                    id: 784302396415422500,
                    id_str: '784302396415422464',
                    text: '@lomadia As someone who was about to buy dollars for their first holiday in years, Mr. Unicycle can fuck off into the sea..',
                    truncated: false,
                    entities: [Object],
                    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                    in_reply_to_status_id: 784301996186533900,
                    in_reply_to_status_id_str: '784301996186533888',
                    in_reply_to_user_id: 45594696,
                    in_reply_to_user_id_str: '45594696',
                    in_reply_to_screen_name: 'lomadia',
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 0,
                    favorite_count: 3,
                    favorited: false,
                    retweeted: false,
                    lang: 'en'
                },
                retweet_count: 0,
                favorite_count: 3,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:59:02 +0000 2016',
                id: 784301996186533900,
                id_str: '784301996186533888',
                text: 'Mate, I\'m LIVING it. And I can read thanks, I watched May cause that weekend fall. https://t.co/hwQF2Bhp2l',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 45594696,
                    id_str: '45594696',
                    name: 'Hannibal Lecterford',
                    screen_name: 'lomadia',
                    location: 'UK',
                    description: 'Gamer, cat lover, really likes raiding tombs - an unhealthy amount. Also a bit of a hoarder. I also stream on Twitch! Artwork by @NinaSerena & @ScribbleToons',
                    url: 'https://t.co/RTpHrjTQzo',
                    entities: [Object],
                    protected: false,
                    followers_count: 198946,
                    friends_count: 579,
                    listed_count: 584,
                    created_at: 'Mon Jun 08 15:50:33 +0000 2009',
                    favourites_count: 9556,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 38717,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '2D0F07',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/45594696/1466445904',
                    profile_link_color: '1E6D7D',
                    profile_sidebar_border_color: '000000',
                    profile_sidebar_fill_color: '180703',
                    profile_text_color: 'AB5F24',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: true,
                quoted_status_id: 784301027369504800,
                quoted_status_id_str: '784301027369504768',
                quoted_status:
                {
                    created_at: 'Fri Oct 07 07:55:11 +0000 2016',
                    id: 784301027369504800,
                    id_str: '784301027369504768',
                    text: '@lomadia guess you didn\'t read it then, oh well',
                    truncated: false,
                    entities: [Object],
                    source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
                    in_reply_to_status_id: 784299866176446500,
                    in_reply_to_status_id_str: '784299866176446464',
                    in_reply_to_user_id: 45594696,
                    in_reply_to_user_id_str: '45594696',
                    in_reply_to_screen_name: 'lomadia',
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 0,
                    favorite_count: 0,
                    favorited: false,
                    retweeted: false,
                    lang: 'en'
                },
                retweet_count: 1,
                favorite_count: 9,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:50:34 +0000 2016',
                id: 784299866176446500,
                id_str: '784299866176446464',
                text: 'Hahahaha hahahaha. Hah. Hah. Hnghhhhh. https://t.co/g6dA9XutvE',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 45594696,
                    id_str: '45594696',
                    name: 'Hannibal Lecterford',
                    screen_name: 'lomadia',
                    location: 'UK',
                    description: 'Gamer, cat lover, really likes raiding tombs - an unhealthy amount. Also a bit of a hoarder. I also stream on Twitch! Artwork by @NinaSerena & @ScribbleToons',
                    url: 'https://t.co/RTpHrjTQzo',
                    entities: [Object],
                    protected: false,
                    followers_count: 198946,
                    friends_count: 579,
                    listed_count: 584,
                    created_at: 'Mon Jun 08 15:50:33 +0000 2009',
                    favourites_count: 9556,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 38717,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '2D0F07',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/45594696/1466445904',
                    profile_link_color: '1E6D7D',
                    profile_sidebar_border_color: '000000',
                    profile_sidebar_fill_color: '180703',
                    profile_text_color: 'AB5F24',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: true,
                quoted_status_id: 784292900125282300,
                quoted_status_id_str: '784292900125282304',
                quoted_status:
                {
                    created_at: 'Fri Oct 07 07:22:53 +0000 2016',
                    id: 784292900125282300,
                    id_str: '784292900125282304',
                    text: '@lomadia oh no I got the sarcasm just the article is not as bad as you are making out',
                    truncated: false,
                    entities: [Object],
                    source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
                    in_reply_to_status_id: 784292359571812400,
                    in_reply_to_status_id_str: '784292359571812352',
                    in_reply_to_user_id: 45594696,
                    in_reply_to_user_id_str: '45594696',
                    in_reply_to_screen_name: 'lomadia',
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 0,
                    favorite_count: 1,
                    favorited: false,
                    retweeted: false,
                    lang: 'en'
                },
                retweet_count: 0,
                favorite_count: 14,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'tl'
            },
            {
                created_at: 'Fri Oct 07 07:49:55 +0000 2016',
                id: 784299704251134000,
                id_str: '784299704251133952',
                text: 'Every time I find a talented Minecraft creator not using social media effectively, I suppress an urge to make and run an account for them.',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
                source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 180670967,
                    id_str: '180670967',
                    name: 'Marc Watson',
                    screen_name: 'Marc_IRL',
                    location: 'Stockholm, Sweden',
                    description: '@Minecraft Realms content manager. Not a developer. Tweeting ideas at @NewMapIdeas. M:tG superfan. American living in Sweden. I stream Minecraft on Fridays!',
                    url: 'https://t.co/ic6MwwfIzf',
                    entities: [Object],
                    protected: false,
                    followers_count: 237765,
                    friends_count: 262,
                    listed_count: 883,
                    created_at: 'Fri Aug 20 05:20:14 +0000 2010',
                    favourites_count: 1997,
                    utc_offset: 7200,
                    time_zone: 'Stockholm',
                    geo_enabled: true,
                    verified: false,
                    statuses_count: 40111,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '1A1B1F',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/789950359/272d240564f0dd738445e7c03de9abf1.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/789950359/272d240564f0dd738445e7c03de9abf1.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781291405771550720/igHycHOF_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781291405771550720/igHycHOF_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/180670967/1465911284',
                    profile_link_color: '2FC2EF',
                    profile_sidebar_border_color: 'FFFFFF',
                    profile_sidebar_fill_color: '252429',
                    profile_text_color: '666666',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: false,
                retweet_count: 1,
                favorite_count: 26,
                favorited: false,
                retweeted: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:42:01 +0000 2016',
                id: 784297714745913300,
                id_str: '784297714745913344',
                text: 'Oh, it gross quite a lot. https://t.co/VOtgXu93hx',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
                source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 63485337,
                    id_str: '63485337',
                    name: 'Notch',
                    screen_name: 'notch',
                    location: '',
                    description: '',
                    url: null,
                    entities: [Object],
                    protected: false,
                    followers_count: 3795870,
                    friends_count: 20,
                    listed_count: 12806,
                    created_at: 'Thu Aug 06 17:08:06 +0000 2009',
                    favourites_count: 29,
                    utc_offset: 7200,
                    time_zone: 'Stockholm',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 41059,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/425547880/bg.png',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/425547880/bg.png',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/784111549514412034/w2_WmQ-H_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/784111549514412034/w2_WmQ-H_normal.jpg',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'C0DEED',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: false,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: true,
                quoted_status_id: 784297098535546900,
                quoted_status_id_str: '784297098535546881',
                quoted_status:
                {
                    created_at: 'Fri Oct 07 07:39:34 +0000 2016',
                    id: 784297098535546900,
                    id_str: '784297098535546881',
                    text: '@notch gross',
                    truncated: false,
                    entities: [Object],
                    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                    in_reply_to_status_id: 784293163930300400,
                    in_reply_to_status_id_str: '784293163930300416',
                    in_reply_to_user_id: 63485337,
                    in_reply_to_user_id_str: '63485337',
                    in_reply_to_screen_name: 'notch',
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 0,
                    favorite_count: 1,
                    favorited: false,
                    retweeted: false,
                    lang: 'en'
                },
                retweet_count: 2,
                favorite_count: 24,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:34:34 +0000 2016',
                id: 784295840558882800,
                id_str: '784295840558882816',
                text: 'This is all getting very real now. https://t.co/ZkYp1KjUAy',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 243662948,
                    id_str: '243662948',
                    name: 'Richard Hammond',
                    screen_name: 'RichardHammond',
                    location: '',
                    description: 'Recently re-employed car show bloke. \nHas own bicycle.',
                    url: 'http://t.co/GobGurZQVf',
                    entities: [Object],
                    protected: false,
                    followers_count: 2849076,
                    friends_count: 133,
                    listed_count: 6257,
                    created_at: 'Thu Jan 27 15:03:53 +0000 2011',
                    favourites_count: 19,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: true,
                    verified: true,
                    statuses_count: 2535,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
                    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/511975267670454272/pDDs6Z-w_normal.jpeg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/511975267670454272/pDDs6Z-w_normal.jpeg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/243662948/1395078471',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'C0DEED',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: false,
                    default_profile: true,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: true,
                quoted_status_id: 784274142304493600,
                quoted_status_id_str: '784274142304493568',
                quoted_status:
                {
                    created_at: 'Fri Oct 07 06:08:21 +0000 2016',
                    id: 784274142304493600,
                    id_str: '784274142304493568',
                    text: 'This could be so expensive… #TheGrandTour streams weekly on Amazon Prime Video beginning 18th of November. https://t.co/SXUeCHwryq',
                    truncated: false,
                    entities: [Object],
                    extended_entities: [Object],
                    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                    in_reply_to_status_id: null,
                    in_reply_to_status_id_str: null,
                    in_reply_to_user_id: null,
                    in_reply_to_user_id_str: null,
                    in_reply_to_screen_name: null,
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 1951,
                    favorite_count: 2806,
                    favorited: false,
                    retweeted: false,
                    possibly_sensitive: false,
                    possibly_sensitive_appealable: false,
                    lang: 'en'
                },
                retweet_count: 329,
                favorite_count: 1051,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:26:17 +0000 2016',
                id: 784293755234820100,
                id_str: '784293755234820097',
                text: 'NONO IT\'S FINE, PR TEAM ARE GONNA RESEND - WE CAN STILL CIV 6!! https://t.co/mZFNK4tmiR',
                truncated: false,
                entities:
                {
                    hashtags: [],
                    symbols: [],
                    user_mentions: [],
                    urls: [],
                    media: [Object]
                },
                extended_entities: { media: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 45594696,
                    id_str: '45594696',
                    name: 'Hannibal Lecterford',
                    screen_name: 'lomadia',
                    location: 'UK',
                    description: 'Gamer, cat lover, really likes raiding tombs - an unhealthy amount. Also a bit of a hoarder. I also stream on Twitch! Artwork by @NinaSerena & @ScribbleToons',
                    url: 'https://t.co/RTpHrjTQzo',
                    entities: [Object],
                    protected: false,
                    followers_count: 198946,
                    friends_count: 579,
                    listed_count: 584,
                    created_at: 'Mon Jun 08 15:50:33 +0000 2009',
                    favourites_count: 9556,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 38717,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '2D0F07',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/45594696/1466445904',
                    profile_link_color: '1E6D7D',
                    profile_sidebar_border_color: '000000',
                    profile_sidebar_fill_color: '180703',
                    profile_text_color: 'AB5F24',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: false,
                retweet_count: 1,
                favorite_count: 54,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:25:22 +0000 2016',
                id: 784293526972489700,
                id_str: '784293526972489728',
                text: 'RT @IggyMF: @notch : Is the underside of an elephant its belly or its chest? It\'s a huge grey area.',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
                source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 63485337,
                    id_str: '63485337',
                    name: 'Notch',
                    screen_name: 'notch',
                    location: '',
                    description: '',
                    url: null,
                    entities: [Object],
                    protected: false,
                    followers_count: 3795870,
                    friends_count: 20,
                    listed_count: 12806,
                    created_at: 'Thu Aug 06 17:08:06 +0000 2009',
                    favourites_count: 29,
                    utc_offset: 7200,
                    time_zone: 'Stockholm',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 41059,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/425547880/bg.png',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/425547880/bg.png',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/784111549514412034/w2_WmQ-H_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/784111549514412034/w2_WmQ-H_normal.jpg',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'C0DEED',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: false,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                retweeted_status:
                {
                    created_at: 'Fri Oct 07 07:25:07 +0000 2016',
                    id: 784293462405320700,
                    id_str: '784293462405320706',
                    text: '@notch : Is the underside of an elephant its belly or its chest? It\'s a huge grey area.',
                    truncated: false,
                    entities: [Object],
                    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                    in_reply_to_status_id: 784292384808972300,
                    in_reply_to_status_id_str: '784292384808972294',
                    in_reply_to_user_id: 63485337,
                    in_reply_to_user_id_str: '63485337',
                    in_reply_to_screen_name: 'notch',
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 41,
                    favorite_count: 129,
                    favorited: false,
                    retweeted: false,
                    lang: 'en'
                },
                is_quote_status: false,
                retweet_count: 41,
                favorite_count: 0,
                favorited: false,
                retweeted: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:25:10 +0000 2016',
                id: 784293476082921500,
                id_str: '784293476082921474',
                text: 'RT @SeargeDP: The recording of our plugins and addons panel at Minecon is now live on the Mojang Youtube channel at https://t.co/8wKdBxQySK',
                truncated: false,
                entities:
                {
                    hashtags: [],
                    symbols: [],
                    user_mentions: [Object],
                    urls: [Object]
                },
                source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 180670967,
                    id_str: '180670967',
                    name: 'Marc Watson',
                    screen_name: 'Marc_IRL',
                    location: 'Stockholm, Sweden',
                    description: '@Minecraft Realms content manager. Not a developer. Tweeting ideas at @NewMapIdeas. M:tG superfan. American living in Sweden. I stream Minecraft on Fridays!',
                    url: 'https://t.co/ic6MwwfIzf',
                    entities: [Object],
                    protected: false,
                    followers_count: 237765,
                    friends_count: 262,
                    listed_count: 883,
                    created_at: 'Fri Aug 20 05:20:14 +0000 2010',
                    favourites_count: 1997,
                    utc_offset: 7200,
                    time_zone: 'Stockholm',
                    geo_enabled: true,
                    verified: false,
                    statuses_count: 40111,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '1A1B1F',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/789950359/272d240564f0dd738445e7c03de9abf1.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/789950359/272d240564f0dd738445e7c03de9abf1.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781291405771550720/igHycHOF_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781291405771550720/igHycHOF_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/180670967/1465911284',
                    profile_link_color: '2FC2EF',
                    profile_sidebar_border_color: 'FFFFFF',
                    profile_sidebar_fill_color: '252429',
                    profile_text_color: '666666',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                retweeted_status:
                {
                    created_at: 'Fri Oct 07 05:00:00 +0000 2016',
                    id: 784256941589602300,
                    id_str: '784256941589602305',
                    text: 'The recording of our plugins and addons panel at Minecon is now live on the Mojang Youtube channel at https://t.co/8wKdBxQySK',
                    truncated: false,
                    entities: [Object],
                    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                    in_reply_to_status_id: null,
                    in_reply_to_status_id_str: null,
                    in_reply_to_user_id: null,
                    in_reply_to_user_id_str: null,
                    in_reply_to_screen_name: null,
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 8,
                    favorite_count: 39,
                    favorited: false,
                    retweeted: false,
                    possibly_sensitive: false,
                    possibly_sensitive_appealable: false,
                    lang: 'en'
                },
                is_quote_status: false,
                retweet_count: 8,
                favorite_count: 0,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:23:56 +0000 2016',
                id: 784293163930300400,
                id_str: '784293163930300416',
                text: 'Nevermind, I fingered it out.',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
                source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 63485337,
                    id_str: '63485337',
                    name: 'Notch',
                    screen_name: 'notch',
                    location: '',
                    description: '',
                    url: null,
                    entities: [Object],
                    protected: false,
                    followers_count: 3795870,
                    friends_count: 20,
                    listed_count: 12806,
                    created_at: 'Thu Aug 06 17:08:06 +0000 2009',
                    favourites_count: 29,
                    utc_offset: 7200,
                    time_zone: 'Stockholm',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 41059,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/425547880/bg.png',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/425547880/bg.png',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/784111549514412034/w2_WmQ-H_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/784111549514412034/w2_WmQ-H_normal.jpg',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'C0DEED',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: false,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: false,
                retweet_count: 27,
                favorite_count: 148,
                favorited: false,
                retweeted: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:22:00 +0000 2016',
                id: 784292679764938800,
                id_str: '784292679764938753',
                text: 'Went into Yogtowers early so the computer was free to install @CivGame - the special unique code had an expiration date. FML. Stay tuned!',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 45594696,
                    id_str: '45594696',
                    name: 'Hannibal Lecterford',
                    screen_name: 'lomadia',
                    location: 'UK',
                    description: 'Gamer, cat lover, really likes raiding tombs - an unhealthy amount. Also a bit of a hoarder. I also stream on Twitch! Artwork by @NinaSerena & @ScribbleToons',
                    url: 'https://t.co/RTpHrjTQzo',
                    entities: [Object],
                    protected: false,
                    followers_count: 198946,
                    friends_count: 579,
                    listed_count: 584,
                    created_at: 'Mon Jun 08 15:50:33 +0000 2009',
                    favourites_count: 9556,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 38717,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '2D0F07',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/45594696/1466445904',
                    profile_link_color: '1E6D7D',
                    profile_sidebar_border_color: '000000',
                    profile_sidebar_fill_color: '180703',
                    profile_text_color: 'AB5F24',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: false,
                retweet_count: 1,
                favorite_count: 31,
                favorited: false,
                retweeted: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:20:50 +0000 2016',
                id: 784292384808972300,
                id_str: '784292384808972294',
                text: 'Something tells me the light switch is placed too high, but I can\'t quite put my finger on it.',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
                source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 63485337,
                    id_str: '63485337',
                    name: 'Notch',
                    screen_name: 'notch',
                    location: '',
                    description: '',
                    url: null,
                    entities: [Object],
                    protected: false,
                    followers_count: 3795870,
                    friends_count: 20,
                    listed_count: 12806,
                    created_at: 'Thu Aug 06 17:08:06 +0000 2009',
                    favourites_count: 29,
                    utc_offset: 7200,
                    time_zone: 'Stockholm',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 41059,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/425547880/bg.png',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/425547880/bg.png',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/784111549514412034/w2_WmQ-H_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/784111549514412034/w2_WmQ-H_normal.jpg',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'C0DEED',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: false,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: false,
                retweet_count: 54,
                favorite_count: 222,
                favorited: false,
                retweeted: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:07:52 +0000 2016',
                id: 784289120474443800,
                id_str: '784289120474443777',
                text: 'Recorded wind speeds at airports along the Florida coast in the last 20 minutes. \n\nhttps://t.co/DxytyvHVjv https://t.co/AQ8x4BJd4r',
                truncated: false,
                entities:
                {
                    hashtags: [],
                    symbols: [],
                    user_mentions: [],
                    urls: [Object],
                    media: [Object]
                },
                extended_entities: { media: [Object] },
                source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 134196350,
                    id_str: '134196350',
                    name: 'Flightradar24',
                    screen_name: 'flightradar24',
                    location: 'Stockholm, Sweden',
                    description: 'Track air traffic in real time from all around the world! Apps: http://t.co/ongfnAPfLz\nFAQ: http://t.co/WfQImBHLYe\nSupport: http://t.co/ifn4x04sH9',
                    url: 'http://t.co/lEiMiBrCZi',
                    entities: [Object],
                    protected: false,
                    followers_count: 331433,
                    friends_count: 504,
                    listed_count: 3661,
                    created_at: 'Sat Apr 17 18:27:21 +0000 2010',
                    favourites_count: 3832,
                    utc_offset: 7200,
                    time_zone: 'Stockholm',
                    geo_enabled: true,
                    verified: true,
                    statuses_count: 17797,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/668938936/b5236e4d272f3ad2edc4ada63dd21f11.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/668938936/b5236e4d272f3ad2edc4ada63dd21f11.jpeg',
                    profile_background_tile: true,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/710502600593035265/eU_SCiU9_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/710502600593035265/eU_SCiU9_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/134196350/1458233614',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'FFFFFF',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: false,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: false,
                retweet_count: 41,
                favorite_count: 31,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:07:39 +0000 2016',
                id: 784289065482883100,
                id_str: '784289065482883072',
                text: 'RT @kylegriffin1: New: 30 former GOP members of Congress come out against Trump, saying they won\'t vote for him. https://t.co/7H3Nyi5pDI',
                truncated: false,
                entities:
                {
                    hashtags: [],
                    symbols: [],
                    user_mentions: [Object],
                    urls: [],
                    media: [Object]
                },
                extended_entities: { media: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 45594696,
                    id_str: '45594696',
                    name: 'Hannibal Lecterford',
                    screen_name: 'lomadia',
                    location: 'UK',
                    description: 'Gamer, cat lover, really likes raiding tombs - an unhealthy amount. Also a bit of a hoarder. I also stream on Twitch! Artwork by @NinaSerena & @ScribbleToons',
                    url: 'https://t.co/RTpHrjTQzo',
                    entities: [Object],
                    protected: false,
                    followers_count: 198946,
                    friends_count: 579,
                    listed_count: 584,
                    created_at: 'Mon Jun 08 15:50:33 +0000 2009',
                    favourites_count: 9556,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 38717,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '2D0F07',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/45594696/1466445904',
                    profile_link_color: '1E6D7D',
                    profile_sidebar_border_color: '000000',
                    profile_sidebar_fill_color: '180703',
                    profile_text_color: 'AB5F24',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                retweeted_status:
                {
                    created_at: 'Thu Oct 06 15:07:53 +0000 2016',
                    id: 784047532833923100,
                    id_str: '784047532833923072',
                    text: 'New: 30 former GOP members of Congress come out against Trump, saying they won\'t vote for him. https://t.co/7H3Nyi5pDI',
                    truncated: false,
                    entities: [Object],
                    extended_entities: [Object],
                    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                    in_reply_to_status_id: null,
                    in_reply_to_status_id_str: null,
                    in_reply_to_user_id: null,
                    in_reply_to_user_id_str: null,
                    in_reply_to_screen_name: null,
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 1657,
                    favorite_count: 1918,
                    favorited: false,
                    retweeted: false,
                    possibly_sensitive: false,
                    possibly_sensitive_appealable: false,
                    lang: 'en'
                },
                is_quote_status: false,
                retweet_count: 1657,
                favorite_count: 0,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:06:54 +0000 2016',
                id: 784288877326454800,
                id_str: '784288877326454784',
                text: 'RT @JamesMelville: Tories see immigrants as the enemy within - even those who save our lives, care for us and educate us. \nAppalling. https…',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 45594696,
                    id_str: '45594696',
                    name: 'Hannibal Lecterford',
                    screen_name: 'lomadia',
                    location: 'UK',
                    description: 'Gamer, cat lover, really likes raiding tombs - an unhealthy amount. Also a bit of a hoarder. I also stream on Twitch! Artwork by @NinaSerena & @ScribbleToons',
                    url: 'https://t.co/RTpHrjTQzo',
                    entities: [Object],
                    protected: false,
                    followers_count: 198946,
                    friends_count: 579,
                    listed_count: 584,
                    created_at: 'Mon Jun 08 15:50:33 +0000 2009',
                    favourites_count: 9556,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 38717,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '2D0F07',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/45594696/1466445904',
                    profile_link_color: '1E6D7D',
                    profile_sidebar_border_color: '000000',
                    profile_sidebar_fill_color: '180703',
                    profile_text_color: 'AB5F24',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                retweeted_status:
                {
                    created_at: 'Thu Oct 06 07:46:57 +0000 2016',
                    id: 783936568490860500,
                    id_str: '783936568490860544',
                    text: 'Tories see immigrants as the enemy within - even those who save our lives, care for us and educate us. \nAppalling. https://t.co/B46571i34d',
                    truncated: false,
                    entities: [Object],
                    extended_entities: [Object],
                    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                    in_reply_to_status_id: null,
                    in_reply_to_status_id_str: null,
                    in_reply_to_user_id: null,
                    in_reply_to_user_id_str: null,
                    in_reply_to_screen_name: null,
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 1365,
                    favorite_count: 1013,
                    favorited: false,
                    retweeted: false,
                    possibly_sensitive: false,
                    possibly_sensitive_appealable: false,
                    lang: 'en'
                },
                is_quote_status: false,
                retweet_count: 1365,
                favorite_count: 0,
                favorited: false,
                retweeted: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 07:04:29 +0000 2016',
                id: 784288270439948300,
                id_str: '784288270439948289',
                text: 'Great job everyone, keep it up � https://t.co/c4wPKBnfs1',
                truncated: false,
                entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 45594696,
                    id_str: '45594696',
                    name: 'Hannibal Lecterford',
                    screen_name: 'lomadia',
                    location: 'UK',
                    description: 'Gamer, cat lover, really likes raiding tombs - an unhealthy amount. Also a bit of a hoarder. I also stream on Twitch! Artwork by @NinaSerena & @ScribbleToons',
                    url: 'https://t.co/RTpHrjTQzo',
                    entities: [Object],
                    protected: false,
                    followers_count: 198946,
                    friends_count: 579,
                    listed_count: 584,
                    created_at: 'Mon Jun 08 15:50:33 +0000 2009',
                    favourites_count: 9556,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 38717,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: '2D0F07',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/839749274/678caa77a6b543774154942b9e839e6b.jpeg',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/781487019595816960/EeLyY9R4_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/45594696/1466445904',
                    profile_link_color: '1E6D7D',
                    profile_sidebar_border_color: '000000',
                    profile_sidebar_fill_color: '180703',
                    profile_text_color: 'AB5F24',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: true,
                quoted_status_id: 784200374127329300,
                quoted_status_id_str: '784200374127329280',
                quoted_status:
                {
                    created_at: 'Fri Oct 07 01:15:13 +0000 2016',
                    id: 784200374127329300,
                    id_str: '784200374127329280',
                    text: 'British pound plunges through $1.20 for the first time since May 1985 https://t.co/6USSNM2KZO https://t.co/IkCOPqIk92',
                    truncated: false,
                    entities: [Object],
                    extended_entities: [Object],
                    source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
                    in_reply_to_status_id: null,
                    in_reply_to_status_id_str: null,
                    in_reply_to_user_id: null,
                    in_reply_to_user_id_str: null,
                    in_reply_to_screen_name: null,
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 447,
                    favorite_count: 137,
                    favorited: false,
                    retweeted: false,
                    possibly_sensitive: false,
                    possibly_sensitive_appealable: false,
                    lang: 'en'
                },
                retweet_count: 12,
                favorite_count: 56,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 06:34:15 +0000 2016',
                id: 784280662710726700,
                id_str: '784280662710726657',
                text: 'More Hurricane hunting for #NOAA49 ‘Gonzo’. \n\n� https://t.co/96WbwBwfzT\n\n#HurricaneMatthew https://t.co/iYxo4DFrPM',
                truncated: false,
                entities:
                {
                    hashtags: [Object],
                    symbols: [],
                    user_mentions: [],
                    urls: [Object],
                    media: [Object]
                },
                extended_entities: { media: [Object] },
                source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 134196350,
                    id_str: '134196350',
                    name: 'Flightradar24',
                    screen_name: 'flightradar24',
                    location: 'Stockholm, Sweden',
                    description: 'Track air traffic in real time from all around the world! Apps: http://t.co/ongfnAPfLz\nFAQ: http://t.co/WfQImBHLYe\nSupport: http://t.co/ifn4x04sH9',
                    url: 'http://t.co/lEiMiBrCZi',
                    entities: [Object],
                    protected: false,
                    followers_count: 331433,
                    friends_count: 504,
                    listed_count: 3661,
                    created_at: 'Sat Apr 17 18:27:21 +0000 2010',
                    favourites_count: 3832,
                    utc_offset: 7200,
                    time_zone: 'Stockholm',
                    geo_enabled: true,
                    verified: true,
                    statuses_count: 17797,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/668938936/b5236e4d272f3ad2edc4ada63dd21f11.jpeg',
                    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/668938936/b5236e4d272f3ad2edc4ada63dd21f11.jpeg',
                    profile_background_tile: true,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/710502600593035265/eU_SCiU9_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/710502600593035265/eU_SCiU9_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/134196350/1458233614',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'FFFFFF',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: false,
                    default_profile: false,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                is_quote_status: false,
                retweet_count: 48,
                favorite_count: 34,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 06:26:13 +0000 2016',
                id: 784278639802093600,
                id_str: '784278639802093568',
                text: 'RT @scottjohnson: The stuff I get. https://t.co/AcqiklcqrE',
                truncated: false,
                entities:
                {
                    hashtags: [],
                    symbols: [],
                    user_mentions: [Object],
                    urls: [],
                    media: [Object]
                },
                extended_entities: { media: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 14368093,
                    id_str: '14368093',
                    name: 'Turps',
                    screen_name: 'The_T',
                    location: 'Bristol, England',
                    description: 'Podcaster, Gamer and Yognaught',
                    url: 'https://t.co/SjiqZWhLfF',
                    entities: [Object],
                    protected: false,
                    followers_count: 151236,
                    friends_count: 549,
                    listed_count: 1117,
                    created_at: 'Sat Apr 12 10:12:34 +0000 2008',
                    favourites_count: 79,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 17419,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
                    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/721758693600141314/ZKT1oEJT_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/721758693600141314/ZKT1oEJT_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/14368093/1460915621',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'C0DEED',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: true,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                retweeted_status:
                {
                    created_at: 'Fri Oct 07 05:18:11 +0000 2016',
                    id: 784261519441670100,
                    id_str: '784261519441670144',
                    text: 'The stuff I get. https://t.co/AcqiklcqrE',
                    truncated: false,
                    entities: [Object],
                    extended_entities: [Object],
                    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                    in_reply_to_status_id: null,
                    in_reply_to_status_id_str: null,
                    in_reply_to_user_id: null,
                    in_reply_to_user_id_str: null,
                    in_reply_to_screen_name: null,
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 5,
                    favorite_count: 44,
                    favorited: false,
                    retweeted: false,
                    possibly_sensitive: false,
                    possibly_sensitive_appealable: false,
                    lang: 'en'
                },
                is_quote_status: false,
                retweet_count: 5,
                favorite_count: 0,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 06:25:26 +0000 2016',
                id: 784278443546464300,
                id_str: '784278443546464256',
                text: 'RT @DankQueso4l: @scottjohnson @The_T when the lore episode is just right https://t.co/Ykuah7RhHL',
                truncated: false,
                entities:
                {
                    hashtags: [],
                    symbols: [],
                    user_mentions: [Object],
                    urls: [],
                    media: [Object]
                },
                extended_entities: { media: [Object] },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 14368093,
                    id_str: '14368093',
                    name: 'Turps',
                    screen_name: 'The_T',
                    location: 'Bristol, England',
                    description: 'Podcaster, Gamer and Yognaught',
                    url: 'https://t.co/SjiqZWhLfF',
                    entities: [Object],
                    protected: false,
                    followers_count: 151236,
                    friends_count: 549,
                    listed_count: 1117,
                    created_at: 'Sat Apr 12 10:12:34 +0000 2008',
                    favourites_count: 79,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 17419,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
                    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/721758693600141314/ZKT1oEJT_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/721758693600141314/ZKT1oEJT_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/14368093/1460915621',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'C0DEED',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: true,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                retweeted_status:
                {
                    created_at: 'Fri Oct 07 05:00:13 +0000 2016',
                    id: 784256997176729600,
                    id_str: '784256997176729604',
                    text: '@scottjohnson @The_T when the lore episode is just right https://t.co/Ykuah7RhHL',
                    truncated: false,
                    entities: [Object],
                    extended_entities: [Object],
                    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
                    in_reply_to_status_id: null,
                    in_reply_to_status_id_str: null,
                    in_reply_to_user_id: 761290,
                    in_reply_to_user_id_str: '761290',
                    in_reply_to_screen_name: 'scottjohnson',
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 2,
                    favorite_count: 22,
                    favorited: false,
                    retweeted: false,
                    possibly_sensitive: false,
                    possibly_sensitive_appealable: false,
                    lang: 'en'
                },
                is_quote_status: false,
                retweet_count: 2,
                favorite_count: 0,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            },
            {
                created_at: 'Fri Oct 07 06:24:15 +0000 2016',
                id: 784278144916140000,
                id_str: '784278144916140032',
                text: 'RT @RiversRubin: Because someone had to take @scottjohnson and @The_T and use their audio to make this... https://t.co/bqR0dU7nYk  #Frogpan…',
                truncated: false,
                entities:
                {
                    hashtags: [],
                    symbols: [],
                    user_mentions: [Object],
                    urls: [Object]
                },
                source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                in_reply_to_status_id: null,
                in_reply_to_status_id_str: null,
                in_reply_to_user_id: null,
                in_reply_to_user_id_str: null,
                in_reply_to_screen_name: null,
                user:
                {
                    id: 14368093,
                    id_str: '14368093',
                    name: 'Turps',
                    screen_name: 'The_T',
                    location: 'Bristol, England',
                    description: 'Podcaster, Gamer and Yognaught',
                    url: 'https://t.co/SjiqZWhLfF',
                    entities: [Object],
                    protected: false,
                    followers_count: 151236,
                    friends_count: 549,
                    listed_count: 1117,
                    created_at: 'Sat Apr 12 10:12:34 +0000 2008',
                    favourites_count: 79,
                    utc_offset: 3600,
                    time_zone: 'London',
                    geo_enabled: false,
                    verified: true,
                    statuses_count: 17419,
                    lang: 'en',
                    contributors_enabled: false,
                    is_translator: false,
                    is_translation_enabled: false,
                    profile_background_color: 'C0DEED',
                    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
                    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
                    profile_background_tile: false,
                    profile_image_url: 'http://pbs.twimg.com/profile_images/721758693600141314/ZKT1oEJT_normal.jpg',
                    profile_image_url_https: 'https://pbs.twimg.com/profile_images/721758693600141314/ZKT1oEJT_normal.jpg',
                    profile_banner_url: 'https://pbs.twimg.com/profile_banners/14368093/1460915621',
                    profile_link_color: '0084B4',
                    profile_sidebar_border_color: 'C0DEED',
                    profile_sidebar_fill_color: 'DDEEF6',
                    profile_text_color: '333333',
                    profile_use_background_image: true,
                    has_extended_profile: true,
                    default_profile: true,
                    default_profile_image: false,
                    following: true,
                    follow_request_sent: false,
                    notifications: false
                },
                geo: null,
                coordinates: null,
                place: null,
                contributors: null,
                retweeted_status:
                {
                    created_at: 'Fri Oct 07 02:51:10 +0000 2016',
                    id: 784224518868987900,
                    id_str: '784224518868987905',
                    text: 'Because someone had to take @scottjohnson and @The_T and use their audio to make this... https://t.co/bqR0dU7nYk  #Frogpants #HypoHelp',
                    truncated: false,
                    entities: [Object],
                    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                    in_reply_to_status_id: null,
                    in_reply_to_status_id_str: null,
                    in_reply_to_user_id: null,
                    in_reply_to_user_id_str: null,
                    in_reply_to_screen_name: null,
                    user: [Object],
                    geo: null,
                    coordinates: null,
                    place: null,
                    contributors: null,
                    is_quote_status: false,
                    retweet_count: 1,
                    favorite_count: 5,
                    favorited: false,
                    retweeted: false,
                    possibly_sensitive: false,
                    possibly_sensitive_appealable: false,
                    lang: 'en'
                },
                is_quote_status: false,
                retweet_count: 1,
                favorite_count: 0,
                favorited: false,
                retweeted: false,
                possibly_sensitive: false,
                possibly_sensitive_appealable: false,
                lang: 'en'
            }]
        });
    }
}